name: Triage Issues
on:
  issues:
    types: [opened]

jobs:
  assignRob:
    name: Assign Rob
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Apply triage label
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['triage']
            })
      - name: Comment On New Issues
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting! @robrbecker will take a look.'
            })
